name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - run: mkdir -p ./dist

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          args: "-g -lualatex -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape"
          working_directory: ./
          latexmk_shell_escape: true
          extra_fonts: |
            ./fonts/*.ttf
          root_file: |
            document.tex

      - name: Upload document
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: document.pdf
